image: node:10.15.3

test api:
  stage: test
  services:
    - name: mysql:8.0.16
      command: ["--default-authentication-plugin=mysql_native_password"]
  variables:
    NODE_ENV: test
    MYSQL_DATABASE: "my-random-db-test"
    MYSQL_ROOT_PASSWORD: "default"
  before_script:
    - apt-get update
    - npm i -g mysql2 sequelize sequelize-cli gulp-cli
    - mysqld --default-authentication-plugin=mysql_native_password
    - cd server/
    - sequelize db:migrate --env test
    - cd ../
    - npm install
    - gulp
  script:
    - npm run unit-test
    - npm run integration-test
